### PR TITLE
fix addNotification

### PR DESCRIPTION
**Pull request by Mte90**
If you try the boilerplate on Firefox, Chrome and the Simulator and click on addNotification nothing happens.

I have integrated the code on https://developer.mozilla.org/en-US/docs/Web/API/notification and tested.
Now on the browser cited above the notification works!

this is the new code that add for the new notification before a check of permission and after show the notification.

```
var addNotification = document.querySelector("#add-notification");
    if (addNotification) {
        addNotification.onclick = function () {
            if ("Notification" in window) {
                // Firefox OS 1.1 and higher

        if (Notification.permission !== 'denied') {
            Notification.requestPermission(function (permission) {
            if(!('permission' in Notification)) {
                Notification.permission = permission;
            }
            });
        }

        if (Notification.permission === "granted") {
            var notification = new Notification("See this", {
            body : "This is a notification"
            });    
        }
            } 
        else {
                // Firefox OS 1.0
                var notification = navigator.mozNotification.createNotification(
                    "See this",
                    "This is a notification"
                );
                notification.show();
            }
        };
    }
```

### CODE REVIEW

**Comment by robnyman** [comment]
Thanks! I'm fine with adding this, but what's up with the changes on a bunch of other lines? Formatting?

**Comment by Mte90** [comment]
i think that it's my editor (netbeans) i posted the function directly to avoid problems.

**Comment by robnyman** [comment]
Thanks! Took the code and pushed it to the repo!
Can you please get the latest version and verify that it works as intended?

**Comment by Mte90** [comment]
Perfect :-D

**Comment by robnyman** [comment]
Awesome, thanks for the help!

**Comment by nikmauro** [comment]
this code working only in browser, not working to mobile (firefox os 1.1 Alcatel touch fire) or firefox os simulator

**Comment by Mte90** [comment]
You are sure?
On my simulator 1.3 and Keon with 1.2 work without problems.
After the enable of the permissions for the notification the code work without problems.

**Pull request closed without merging**
