### PR TITLE
Added an open Web Activity for video

### PR DESCRIPTION
**Pull request by fharper**

### CODE REVIEW

**Comment by robnyman** [comment]
One challenge here, though, is that the video is online (and would probably be too big to embed in the repo). Good ideas how to communicate it?

**Comment by fharper** [comment]
Do we want everything to be offline? I thought it would have been nice to show that you can play remote video too, but there is probably no problem to add the video to the repository. What do you think?

**Comment by robnyman** [comment]
Offline, if possible, But embedding the video would be too much to download etc as well. Maybe some warning text? Haven't tested the experience on a device that's offline, but if yiu think it's decent, then that's ok.

**Comment by fharper** [comment]
It's 287KB, isn't too much? As for a device offline, you'll get a popup from the OS telling the user that the video cannot be played because the server/network failed (or the format isn't supported).

**Comment by robnyman** [comment]
Well, that's not too bad then. Do you have complete rights for that video? Do we need to include any other info?

**Comment by fharper** [comment]
They are free sample from Theora site, so we are good. I'll update the boilerplate with the offline video.

**Comment by robnyman** [comment]
Ok!

**Pull request merged**
